import { Inter } from 'next/font/google'
import ThemeProvider from '@/context/themeContext'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
   title: 'Api Group',
   description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
   return (
      <html lang="es">
         <body className={inter.className}>
            <ThemeProvider>{children}</ThemeProvider>
         </body>
      </html>
   )
}
